### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by sadowskipawel** [fwbrasil/activate-example-play-async#1]
Stacktrace:
type mismatch; found : net.fwbrasil.activate.play.EntityForm[models.Computer] required: play.api.data.Form[net.fwbrasil.activate.entity.map.MutableEntityMap[models.Computer]] Note: net.fwbrasil.activate.play.EntityData[models.Computer] <: net.fwbrasil.activate.entity.map.MutableEntityMap[models.Computer](and net.fwbrasil.activate.play.EntityForm[models.Computer] <: play.api.data.Form[net.fwbrasil.activate.play.EntityData[models.Computer]]), but class Form is invariant in type T. You may wish to define T as +T instead. (SLS 4.5)

**Comment by fwbrasil** [comment]
Could you print here the revision that you are using?
I can't reproduce on master last revision.

**Comment by sadowskipawel** [comment]
Im at work now, but it was on master with play 2.2.0

**Comment by fwbrasil** [comment]
Maybe you have a old activate snapshot on your local repository. Please, do a "sbt update" to see if the problem is solved.
